apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-calls-to-prod
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: deny-prod-namespace-calls
      match:
        any:
          - resources:
              kinds:
                - ClientIntents
      validate:
        message: "Calls to services in the 'prod' namespace are not allowed."
        foreach:
          - list: "request.object.spec.calls"
            deny:
              conditions:
                any:
                  # Deny services that end with .prod (prod namespace)
                  - key: "{{ regex_match('.*\\.prod$', element.name) }}"
                    operator: Equals
                    value: true
