apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: kafka-entity-operator
  namespace: kafka
spec:
  service:
    name: kafka-entity-operator
  calls:
    - name: svc:kubernetes.default
    - name: shifumi-kafka
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: shifumi-client
  namespace: shifumi
spec:
  service:
    name: shifumi-client
  calls:
    - name: shifumi-kafka.kafka
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: shifumi-kafka
  namespace: kafka
spec:
  service:
    name: shifumi-kafka
  calls:
    - name: shifumi-kafka
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: shifumi-server
  namespace: shifumi
spec:
  service:
    name: shifumi-server
  calls:
    - name: shifumi-kafka.kafka
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
spec:
  service:
    name: strimzi-cluster-operator
  calls:
    - name: svc:kubernetes.default
    - name: shifumi-kafka
